// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ghq_nll_groups
Rcpp::List ghq_nll_groups(const NumericVector& etak, const NumericVector& y, const NumericVector& factor, const IntegerVector& gid, const NumericVector& Z, const double tau2, const int family_id, const int link_id, Rcpp::Function linkinv_fun);
RcppExport SEXP _metaGLMM_ghq_nll_groups(SEXP etakSEXP, SEXP ySEXP, SEXP factorSEXP, SEXP gidSEXP, SEXP ZSEXP, SEXP tau2SEXP, SEXP family_idSEXP, SEXP link_idSEXP, SEXP linkinv_funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type etak(etakSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gid(gidSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< const int >::type family_id(family_idSEXP);
    Rcpp::traits::input_parameter< const int >::type link_id(link_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type linkinv_fun(linkinv_funSEXP);
    rcpp_result_gen = Rcpp::wrap(ghq_nll_groups(etak, y, factor, gid, Z, tau2, family_id, link_id, linkinv_fun));
    return rcpp_result_gen;
END_RCPP
}
// mc_nll_groups
List mc_nll_groups(const NumericVector& etak, const NumericVector& y, const NumericVector& factor, const IntegerVector& gid, const NumericVector& Z, const NumericVector& rstdnorm, double tau2, double tau2_min, int fam_code, int link_code);
RcppExport SEXP _metaGLMM_mc_nll_groups(SEXP etakSEXP, SEXP ySEXP, SEXP factorSEXP, SEXP gidSEXP, SEXP ZSEXP, SEXP rstdnormSEXP, SEXP tau2SEXP, SEXP tau2_minSEXP, SEXP fam_codeSEXP, SEXP link_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type etak(etakSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gid(gidSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rstdnorm(rstdnormSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_min(tau2_minSEXP);
    Rcpp::traits::input_parameter< int >::type fam_code(fam_codeSEXP);
    Rcpp::traits::input_parameter< int >::type link_code(link_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_nll_groups(etak, y, factor, gid, Z, rstdnorm, tau2, tau2_min, fam_code, link_code));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metaGLMM_ghq_nll_groups", (DL_FUNC) &_metaGLMM_ghq_nll_groups, 9},
    {"_metaGLMM_mc_nll_groups", (DL_FUNC) &_metaGLMM_mc_nll_groups, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_metaGLMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
