# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ghq_nll_groups_fast <- function(etak, y, factor, Z, gptr, tau2, family_id, link_id, ghq_x, ghq_w, linkinv_fun) {
    .Call(`_metaGLMM_ghq_nll_groups_fast`, etak, y, factor, Z, gptr, tau2, family_id, link_id, ghq_x, ghq_w, linkinv_fun)
}

mc_nll_groups <- function(etak, y, factor, gid, Z, rstdnorm, tau2, tau2_min, fam_code, link_code) {
    .Call(`_metaGLMM_mc_nll_groups`, etak, y, factor, gid, Z, rstdnorm, tau2, tau2_min, fam_code, link_code)
}

